/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2205 from the
 * contents of MyCollator.xs. Do not edit this file, edit MyCollator.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "MyCollator.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include <iostream>
#include <unicode/coll.h>
using namespace std;

class MyCollator {
private:
	Locale* locale;
	Collator* collator;
public:
	MyCollator(const char *language, const char *country=0, const char *variant=0): locale(NULL),collator(NULL) {
		locale = new Locale(language, country, variant);
		if (locale->isBogus()) {
			delete locale;
			locale = NULL;
			croak("Locale not supported");
		}
		/* cout << locale->getLanguage() << endl; */
		UErrorCode err = U_ZERO_ERROR;
		collator = Collator::createInstance(*locale, err);
		if (U_FAILURE(err)) {
			delete locale;
			locale = NULL;
			croak("Unable to create the instance of collator %s\n", u_errorName(err));
		}
		collator->setAttribute(UCOL_CASE_FIRST, UCOL_UPPER_FIRST, err);
		/*collator->setAttribute(UCOL_CASE_LEVEL, UCOL_ON, err); */
	}
	~MyCollator() {
		if (collator) {
		    delete collator;
		}
		if (locale) {
		    delete locale;
		}
	}
	int compare(const char* a, const char* b) {
		UnicodeString strA(a, "utf8");
		UnicodeString strB(b, "utf8");

		UErrorCode err = U_ZERO_ERROR;
		UCollationResult result = collator->compare(strA, strB, err);

		if (U_FAILURE(err)) {
			croak("Unable to compare strings %s\n", u_errorName(err));
		}

		if (result == UCOL_EQUAL) {
			return 0;
		} else if (result == UCOL_GREATER) {
			return 1;
		} else {
			return -1;
		}
	}
};

#line 78 "MyCollator.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 130 "MyCollator.c"

XS(XS_ICU__MyCollator_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_ICU__MyCollator_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 2 || items > 4)
       croak_xs_usage(cv,  "CLASS, language, country=0, variant=0");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0));
	MyCollator *	RETVAL;
	const char *	language = (const char *)SvPV_nolen(ST(1));
	const char *	country;
	const char *	variant;

	if (items < 3)
	    country = 0;
	else {
	    country = (const char *)SvPV_nolen(ST(2));
	}

	if (items < 4)
	    variant = 0;
	else {
	    variant = (const char *)SvPV_nolen(ST(3));
	}

	RETVAL = new MyCollator(language, country, variant);
	ST(0) = sv_newmortal();
	sv_setref_pv( ST(0), CLASS, (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_ICU__MyCollator_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_ICU__MyCollator_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	MyCollator *	THIS;

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (MyCollator *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "ICU::MyCollator::DESTROY() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS(XS_ICU__MyCollator_compare); /* prototype to pass -Wmissing-prototypes */
XS(XS_ICU__MyCollator_compare)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, a, b");
    {
	MyCollator *	THIS;
	int	RETVAL;
	dXSTARG;
	const char*	a = (const char *)SvPV_nolen(ST(1));
	const char*	b = (const char *)SvPV_nolen(ST(2));

	if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
		THIS = (MyCollator *)SvIV((SV*)SvRV( ST(0) ));
	else{
		warn( "ICU::MyCollator::compare() -- THIS is not a blessed SV reference" );
		XSRETURN_UNDEF;
	};

	RETVAL = THIS->compare(a, b);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_ICU__MyCollator); /* prototype to pass -Wmissing-prototypes */
XS(boot_ICU__MyCollator)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("ICU::MyCollator::new", XS_ICU__MyCollator_new, file);
        newXS("ICU::MyCollator::DESTROY", XS_ICU__MyCollator_DESTROY, file);
        newXS("ICU::MyCollator::compare", XS_ICU__MyCollator_compare, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

